name: Fetch chilliwackculturalcentre-ca Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 3' #runs every week on wednesday at noon UTC (around 4 AM PDT)

jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "chilliwackculturalcentre-ca"
          publisher: "https://github.com/fjjulien#this"
          page-url: "https://www.chilliwackculturalcentre.ca/upcoming-events/"
          entity-identifier: "//article//a"
          token: "${{ secrets.GITHUB_TOKEN }}"
