name: Fetch grandsballets-com Events

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 2'
      
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "grandsballets-com"
          publisher: "https://github.com/fjjulien#this"
          downloadFile: "output/grandsballets-com.jsonld"
          page-url: "https://grandsballets.com/"
          token: "${{ secrets.GITHUB_TOKEN }}"
