name: petittheatre-org

on:
  workflow_dispatch:
    
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-test"
          artifact: "petittheatre-org"
          publisher: "${{ vars.CAPACOA_BOT }}"
          page-url: "https://petittheatre.org/tribe_events-sitemap.xml"
          entity-identifier: "loc"
          token: "${{ secrets.GITHUB_TOKEN }}"
