name: placedesarts-com

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 3' #runs every week on Wednesday at 10 AM UTC (around 5 to 6 AM ET)

jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "placedesarts-com"
          publisher: "https://github.com/saumier#this"
          page-url: "https://www.placedesarts.com/sitemaps-1-section-event-1-sitemap-p1.xml"
          entity-identifier: "loc"
          headless: false
          token: "${{ secrets.GITHUB_TOKEN }}"
